package:
    name: odl
    version: "0.5.1"

source:
    git_url: https://github.com/odlgroup/odl
    # git_rev: master  # for testing, put any branch here
    git_rev: v0.5.1  # release

build:
    noarch_python: True

requirements:
    build:
        - python
        - nomkl         # [not win]
        - setuptools
        - future >=0.14
        - numpy >=1.9
        - scipy >=0.14
    run:
        - python
        - nomkl         # [not win]
        - future >=0.14
        - numpy >=1.9
        - scipy >=0.14
        - matplotlib
        - pytest >=3.0.3

test:
    imports:
        - odl
    commands:
        - python -c "import odl; odl.test()"

about:
    home: https://github.com/odlgroup/odl
    license: GPLv3+
    license_file: LICENSE
    summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"

extra:
    maintainers:
        - Jonas Adler (@adler-j)
        - Holger Kohr (@kohr-h)
