package:
    name: odl
    version: "0.5.0"

source:
    git_url: https://github.com/odlgroup/odl
    git_rev: distribute_tests  # for testing, put any branch here
    # git_rev: v0.5.0  # release

build:
    noarch_python: True

requirements:
    build:
        - python
        - nomkl
        - setuptools
        - future >=0.14
        - numpy >=1.9
        - scipy >=0.14
    run:
        - python
        - nomkl
        - future >=0.14
        - numpy >=1.9
        - scipy >=0.14
        - matplotlib
        - pytest >=3.0

test:
    imports:
        - odl

about:
    home: https://github.com/odlgroup/odl
    license: GPLv3+
    license_file: LICENSE
    summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"

extra:
    maintainers:
        - Jonas Adler (@adler-j)
        - Holger Kohr (@kohr-h)
